### ISSUE TITLE
Get blockly out of source control

### ISSUE THREAD

**Issue by lynnaloo** [makenai/robotnik#13]
We can use the blockly Bower module (or npm if we want to use it server-side) and get that folder out of the static resources.

**Comment by makenai** [comment]
Great call! I didn't do this initially because I was under a time constraint and didn't want to spend time figuring out any assumptions the module maintainer made. It was pretty dirty, but I just pulled it in.

My preference is to go the npm route to keep the setup simpler, unless we run into a shortcoming that makes bower a better option.

**Comment by lynnaloo** [comment]
I was just thinking Bower since Blockly is a client-side library, but we could use the npm module go the Browserify/Webpack route as well:
https://www.npmjs.com/package/blockly

I love this project and it's pretty full-featured for something you did in a rush!
